name: Build

on: [ push, pull_request ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 11

      - run: ${{ env.FC }} --version
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          # Disable building for PyPy and 32bit.
          CIBW_SKIP: pp* *-win32 *-manylinux_i686 *musllinux*
          CIBW_TEST_COMMAND: python -m unittest camb.tests.camb_test
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
